### ISSUE TITLE
Install Packages Stuck Initializing

### ISSUE THREAD

**Issue by amacgregor** [apache/incubator-openwhisk-deploy-kube#466] opened 2019-05-18 11:36 UTC
After trying to deploy with helm the deployment process gets stuck as follows:

```
kubectl get all -n openwhisk -o wide    
NAME                                          READY     STATUS      RESTARTS   AGE       IP          NODE
pod/owdev-alarmprovider-6577b58c95-z72jd      1/1       Running     0          6m        10.1.0.59   docker-for-desktop
pod/owdev-apigateway-cfc9f5f45-grbxg          1/1       Running     0          6m        10.1.0.57   docker-for-desktop
pod/owdev-cloudantprovider-69c46455c9-dg8w4   1/1       Running     0          6m        10.1.0.60   docker-for-desktop
pod/owdev-controller-0                        1/1       Running     0          6m        10.1.0.53   docker-for-desktop
pod/owdev-couchdb-74b7b46b48-b2qt5            1/1       Running     0          6m        10.1.0.63   docker-for-desktop
pod/owdev-init-couchdb-8bxv8                  0/1       Completed   0          6m        10.1.0.55   docker-for-desktop
pod/owdev-install-packages-pkvff              0/1       Init:0/1    0          6m        10.1.0.54   docker-for-desktop
pod/owdev-kafka-0                             1/1       Running     0          6m        10.1.0.64   docker-for-desktop
pod/owdev-kafkaprovider-68d6d4bb8-b9w8t       1/1       Running     0          6m        10.1.0.58   docker-for-desktop
pod/owdev-nginx-56bb8cfb97-jtrs2              1/1       Running     0          6m        10.1.0.56   docker-for-desktop
pod/owdev-redis-6dbd7d7dbf-tqpmh              1/1       Running     0          6m        10.1.0.61   docker-for-desktop
pod/owdev-tests-package-checker               0/1       Error       0          8h        10.1.0.22   docker-for-desktop
pod/owdev-tests-smoketest                     0/1       Error       0          8h        10.1.0.23   docker-for-desktop
pod/owdev-wskadmin                            1/1       Running     0          6m        10.1.0.52   docker-for-desktop
pod/owdev-zookeeper-0                         1/1       Running     0          6m        10.1.0.62   docker-for-desktop

NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE       SELECTOR
service/owdev-apigateway   ClusterIP   10.108.134.133   <none>        8080/TCP,9000/TCP            6m        name=owdev-apigateway
service/owdev-controller   ClusterIP   10.111.162.6     <none>        8080/TCP                     6m        name=owdev-controller
service/owdev-couchdb      ClusterIP   10.108.133.189   <none>        5984/TCP                     6m        name=owdev-couchdb
service/owdev-kafka        ClusterIP   None             <none>        9092/TCP                     6m        name=owdev-kafka
service/owdev-nginx        NodePort    10.100.205.69    <none>        80:31879/TCP,443:31001/TCP   6m        name=owdev-nginx
service/owdev-redis        ClusterIP   10.107.66.255    <none>        6379/TCP                     6m        name=owdev-redis
service/owdev-zookeeper    ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   6m        name=owdev-zookeeper

NAME                           DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE       CONTAINERS   IMAGES                      SELECTOR
daemonset.apps/owdev-invoker   0         0         0         0            0           <none>          6m        invoker      openwhisk/invoker:d353d26   name=owdev-invoker

NAME                                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS         IMAGES                                        SELECTOR
deployment.apps/owdev-alarmprovider      1         1         1            1           6m        alarmprovider      openwhisk/alarmprovider:2.0.0-incubating      name=owdev-alarmprovider
deployment.apps/owdev-apigateway         1         1         1            1           6m        apigateway         openwhisk/apigateway:993dda2                  name=owdev-apigateway
deployment.apps/owdev-cloudantprovider   1         1         1            1           6m        cloudantprovider   openwhisk/cloudantprovider:2.0.0-incubating   name=owdev-cloudantprovider
deployment.apps/owdev-couchdb            1         1         1            1           6m        couchdb            apache/couchdb:2.3                            name=owdev-couchdb
deployment.apps/owdev-kafkaprovider      1         1         1            1           6m        kafkaprovider      openwhisk/kafkaprovider:2.0.0-incubating      name=owdev-kafkaprovider
deployment.apps/owdev-nginx              1         1         1            1           6m        nginx              nginx:1.15                                    name=owdev-nginx
deployment.apps/owdev-redis              1         1         1            1           6m        redis              redis:4.0                                     name=owdev-redis

NAME                                                DESIRED   CURRENT   READY     AGE       CONTAINERS         IMAGES                                        SELECTOR
replicaset.apps/owdev-alarmprovider-6577b58c95      1         1         1         6m        alarmprovider      openwhisk/alarmprovider:2.0.0-incubating      name=owdev-alarmprovider,pod-template-hash=2133614751
replicaset.apps/owdev-apigateway-cfc9f5f45          1         1         1         6m        apigateway         openwhisk/apigateway:993dda2                  name=owdev-apigateway,pod-template-hash=797591901
replicaset.apps/owdev-cloudantprovider-69c46455c9   1         1         1         6m        cloudantprovider   openwhisk/cloudantprovider:2.0.0-incubating   name=owdev-cloudantprovider,pod-template-hash=2570201175
replicaset.apps/owdev-couchdb-74b7b46b48            1         1         1         6m        couchdb            apache/couchdb:2.3                            name=owdev-couchdb,pod-template-hash=3063602604
replicaset.apps/owdev-kafkaprovider-68d6d4bb8       1         1         1         6m        kafkaprovider      openwhisk/kafkaprovider:2.0.0-incubating      name=owdev-kafkaprovider,pod-template-hash=248280664
replicaset.apps/owdev-nginx-56bb8cfb97              1         1         1         6m        nginx              nginx:1.15                                    name=owdev-nginx,pod-template-hash=1266479653
replicaset.apps/owdev-redis-6dbd7d7dbf              1         1         1         6m        redis              redis:4.0                                     name=owdev-redis,pod-template-hash=2868383869

NAME                                DESIRED   CURRENT   AGE       CONTAINERS   IMAGES
statefulset.apps/owdev-controller   1         1         6m        controller   openwhisk/controller:d353d26
statefulset.apps/owdev-kafka        1         1         6m        kafka        wurstmeister/kafka:0.11.0.1
statefulset.apps/owdev-zookeeper    1         1         6m        zookeeper    zookeeper:3.4

NAME                               DESIRED   SUCCESSFUL   AGE       CONTAINERS         IMAGES                       SELECTOR
job.batch/owdev-init-couchdb       1         1            6m        init-couchdb       openwhisk/ow-utils:d353d26   controller-uid=d2a34bf5-795e-11e9-b725-025000000001
job.batch/owdev-install-packages   1         0            6m        install-packages   openwhisk/ow-utils:d353d26   controller-uid=d2a55bc6-795e-11e9-b725-025000000001```

Checking the status of the pod retrieves the following:

```
kubectl logs job/owdev-install-packages --namespace=openwhisk
Error from server (BadRequest): container "install-packages" in pod "owdev-install-packages-pkvff" is waiting to start: PodInitializing
```

**Comment by csfilipinyi** [comment] 2019-05-20 08:57
I have the very same problem, I tried to install it on EKS. It seems the install-packages gets stuck, but other pods are running fine.

**Comment by aurelienspnll** [comment] 2019-05-20 09:02
Hello, you do not have the pod of the invoker. You have to use the invoker label on the nodes that will execute invokers.
Use this command: `kubectl label nodes --all openwhisk-role=invoker`

**Comment by dgrove-oss** [comment] 2019-05-20 14:05
See also #437.  This is a common user problem, which indicates we need to improve the documentation or install process somehow to make it harder to make this mistake.

**Comment by dgrove-oss** [comment] 2019-05-22 18:39
Closing as duplicate of #437

**Closed by dgrove-oss** 2019-05-22 18:39 UTC

**Comment by reachyunsong** [comment] 2019-06-18 23:35
hi, I have one node as invoker, but owdev-install-packages-tqvll still get stuck.
`sudo kubectl label nodes --all openwhisk-role=invoker
node/node-3.3333.shield-pg0.utah.cloudlab.us labeled
'openwhisk-role' already has a value (core), and --overwrite is false
'openwhisk-role' already has a value (invoker), and --overwrite is false`

**Comment by reachyunsong** [comment] 2019-06-18 23:37
```sudo helm status owdev
LAST DEPLOYED: Tue Jun 18 12:09:38 2019
NAMESPACE: openwhisk
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                         DATA  AGE
owdev-db.config              10    5h16m
owdev-init-couchdb           1     5h16m
owdev-install-packages-cm    1     5h16m
owdev-invoker-scripts        2     5h16m
owdev-nginx                  1     5h16m
owdev-tests-package-checker  1     5h16m
owdev-tests-smoketest        1     5h16m
owdev-whisk.config           9     5h16m
owdev-zookeeper              1     5h16m

==> v1/DaemonSet
NAME           DESIRED  CURRENT  READY  UP-TO-DATE  AVAILABLE  NODE SELECTOR  AGE
owdev-invoker  1        1        1      1           1          <none>         5h16m

==> v1/Deployment
NAME                    READY  UP-TO-DATE  AVAILABLE  AGE
owdev-alarmprovider     1/1    1           1          5h16m
owdev-apigateway        1/1    1           1          5h16m
owdev-cloudantprovider  1/1    1           1          5h16m
owdev-couchdb           1/1    1           1          5h16m
owdev-kafkaprovider     1/1    1           1          5h16m
owdev-nginx             1/1    1           1          5h16m
owdev-redis             1/1    1           1          5h16m

==> v1/Job
NAME                    COMPLETIONS  DURATION  AGE
owdev-init-couchdb      1/1          109s      5h16m
owdev-install-packages  0/1          5h16m     5h16m

==> v1/Pod
NAME            READY  STATUS   RESTARTS  AGE
owdev-wskadmin  1/1    Running  0         5h16m

==> v1/Pod(related)
NAME                                    READY  STATUS     RESTARTS  AGE
owdev-alarmprovider-754b8f648f-nn5rw    1/1    Running    0         5h16m
owdev-apigateway-7644cd4ff-t49rx        1/1    Running    0         5h16m
owdev-cloudantprovider-b9d69f59d-rdtlr  1/1    Running    0         5h16m
owdev-controller-0                      1/1    Running    0         5h16m
owdev-couchdb-58d759dcb9-rcgt9          1/1    Running    0         5h16m
owdev-init-couchdb-krdrg                0/1    Completed  0         5h16m
owdev-install-packages-tqvll            0/1    Init:0/1   0         5h16m
owdev-invoker-dfms4                     1/1    Running    0         5h16m
owdev-kafka-0                           1/1    Running    0         5h16m
owdev-kafkaprovider-55db8d975-g2q4h     1/1    Running    0         5h16m
owdev-nginx-86d777cd8f-fw5fw            1/1    Running    0         5h16m
owdev-redis-6d5466ff6c-lzkj2            1/1    Running    0         5h16m
owdev-zookeeper-0                       1/1    Running    0         5h16m

==> v1/RoleBinding
NAME              AGE
owdev-allow-view  5h16m

==> v1/Secret
NAME                        TYPE    DATA  AGE
owdev-db.auth               Opaque  2     5h16m
owdev-docker.registry.auth  Opaque  2     5h16m
owdev-nginx                 tls     2     5h16m
owdev-whisk.auth            Opaque  2     5h16m

==> v1/Service
NAME              TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)                     AGE
owdev-apigateway  ClusterIP  10.104.254.178  <none>       8080/TCP,9000/TCP           5h16m
owdev-controller  ClusterIP  10.102.116.240  <none>       8080/TCP                    5h16m
owdev-couchdb     ClusterIP  10.98.194.163   <none>       5984/TCP                    5h16m
owdev-kafka       ClusterIP  None            <none>       9092/TCP                    5h16m
owdev-nginx       NodePort   10.99.9.86      <none>       80:32121/TCP,443:31001/TCP  5h16m
owdev-redis       ClusterIP  10.104.119.40   <none>       6379/TCP                    5h16m
owdev-zookeeper   ClusterIP  None            <none>       2181/TCP,2888/TCP,3888/TCP  5h16m

==> v1/ServiceAccount
NAME        SECRETS  AGE
owdev-core  1        5h16m

==> v1/StatefulSet
NAME              READY  AGE
owdev-controller  1/1    5h16m
owdev-kafka       1/1    5h16m
owdev-zookeeper   1/1    5h16m
```
